# Build Stage
FROM golang:1.24-alpine AS builder

WORKDIR /app

{{- if eq .Database "SQLite" }}
# Install build tools for CGO if SQLite is used
RUN apk add --no-cache gcc musl-dev
{{- end }}

COPY go.mod go.sum ./
RUN go mod download

COPY . .

{{- if eq .Database "SQLite" }}
RUN CGO_ENABLED=1 GOOS=linux go build -o main ./cmd/api
{{- else }}
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/api
{{- end }}

# Production Stage
FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add ca-certificates tzdata

COPY --from=builder /app/main .
COPY --from=builder /app/.env.example .env

EXPOSE 8080

CMD ["./main"]
